
INSERT INTO `oper_notify_setting` (`id`, `notify_type`, `field_name`, `field_key`, `field_type`, `max_length`, `required`, `number_decimal`, `enum_type`, `sort_code`, `group_name`, `use_flag`, `created_by`, `created_time`, `last_modified_by`, `last_modified_time`, `delete_flag`) VALUES
	(1, 'notifyGoods', 'TO', 'toContact', 'text', 100, 0, 0, '', 0, '详细信息', 1, NULL, NULL, NULL, NULL, 0),
	(2, 'notifyGoods', 'REF.No', 'refNo', 'text', 100, 0, 0, '', 0, '详细信息', 1, NULL, NULL, NULL, NULL, 0),
	(3, 'notifyGoods', 'HB/L NO.', 'hblNo', 'text', 100, 0, 0, '', 0, '详细信息', 1, NULL, NULL, NULL, NULL, 0),
	(4, 'notifyGoods', 'ATTN', 'attn', 'text', 100, 0, 0, '', 0, '详细信息', 1, NULL, NULL, NULL, NULL, 0),
	(5, 'notifyGoods', 'ATTN电话', 'attnTel', 'text', 100, 0, 0, '', 0, '详细信息', 1, NULL, NULL, NULL, NULL, 0),
	(6, 'notifyGoods', 'ATTN传真', 'attnFax', 'text', 100, 0, 0, '', 0, '详细信息', 1, NULL, NULL, NULL, NULL, 0),
	(7, 'notifyGoods', 'FROM', 'fromContact', 'text', 100, 0, 0, '', 0, '详细信息', 1, NULL, NULL, NULL, NULL, 0),
	(8, 'notifyGoods', 'FROM电话', 'fromTel', 'text', 100, 0, 0, '', 0, '详细信息', 1, NULL, NULL, NULL, NULL, 0),
	(9, 'notifyGoods', 'FROM传真', 'fromFax', 'text', 100, 0, 0, '', 0, '详细信息', 1, NULL, NULL, NULL, NULL, 0),
	(10, 'notifyGoods', 'EMAIL', 'email', 'text', 100, 0, 0, '', 0, '详细信息', 1, NULL, NULL, NULL, NULL, 0),
	(11, 'notifyGoods', '船名', 'vessel', 'text', 100, 0, 0, '', 0, '入货通知详情', 1, NULL, NULL, NULL, NULL, 0),
	(12, 'notifyGoods', '航次', 'notifyGoods', 'text', 100, 0, 0, '', 0, '入货通知详情', 1, NULL, NULL, NULL, NULL, 0),
	(13, 'notifyGoods', '预计船期', 'etd', 'text', 100, 0, 0, '', 0, '入货通知详情', 1, NULL, NULL, NULL, NULL, 0),
	(14, 'notifyGoods', '提单号', 'blNo', 'text', 100, 0, 0, '', 0, '入货通知详情', 1, NULL, NULL, NULL, NULL, 0),
	(15, 'notifyGoods', '目的港', 'destPort', 'text', 100, 0, 0, '', 0, '入货通知详情', 1, NULL, NULL, NULL, NULL, 0),
	(16, 'notifyGoods', '预计截港时间', 'cutOffDate', 'datetime', 100, 0, 0, '', 0, '入货通知详情', 1, NULL, NULL, NULL, NULL, 0),
	(17, 'notifyGoods', '预计截单时间', 'documentaryOffDate', 'datetime', 100, 0, 0, '', 0, '入货通知详情', 1, NULL, NULL, NULL, NULL, 0),
	(18, 'notifyGoods', 'VGM截单时间', 'vgmDocumentaryOffDate', 'date', 100, 0, 0, '', 0, '入货通知详情', 1, NULL, NULL, NULL, NULL, 0),
	(19, 'notifyGoods', '箱量', 'containerQty', 'text', 100, 0, 0, '', 0, '入货通知详情', 1, NULL, NULL, NULL, NULL, 0),
	(20, 'notifyGoods', '温度', 'ctnrTmper', 'text', 100, 0, 0, '', 0, '入货通知详情', 1, NULL, NULL, NULL, NULL, 0),
	(21, 'notifyGoods', '通风', 'ctnrHumidity', 'text', 100, 0, 0, '', 0, '入货通知详情', 1, NULL, NULL, NULL, NULL, 0),
	(22, 'notifyGoods', '湿度', 'ctnrVentilation', 'text', 100, 0, 0, '', 0, '入货通知详情', 1, NULL, NULL, NULL, NULL, 0),
	(23, 'notifyGoods', '用箱备注', 'remark', 'text', 100, 0, 0, '', 0, '入货通知详情', 1, NULL, NULL, NULL, NULL, 0),
	(24, 'notifyGoods', '毛重', 'grossWeight', 'text', 100, 0, 0, '', 0, '入货通知详情', 1, NULL, NULL, NULL, NULL, 0),
	(25, 'notifyGoods', '中文品名', 'chName', 'text', 100, 0, 0, '', 0, '入货通知详情', 1, NULL, NULL, NULL, NULL, 0),
	(26, 'notifyGoods', '危品编号', 'hazardCode', 'text', 100, 0, 0, '', 0, '入货通知详情', 1, NULL, NULL, NULL, NULL, 0),
	(27, 'notifyGoods', '场站', 'loadName', 'text', 100, 0, 0, '', 0, '入货通知详情', 1, NULL, NULL, NULL, NULL, 0),
	(28, 'notifyGoods', '场站联系人', 'loadContact', 'text', 100, 0, 0, '', 0, '入货通知详情', 1, NULL, NULL, NULL, NULL, 0),
	(29, 'notifyGoods', '联系电话', 'loadTel', 'text', 100, 0, 0, '', 0, '入货通知详情', 1, NULL, NULL, NULL, NULL, 0),
	(30, 'notifyGoods', '场站传真', 'loadFax', 'text', 100, 0, 0, '', 0, '入货通知详情', 1, NULL, NULL, NULL, NULL, 0),
	(31, 'notifyGoods', '场站地址', 'loadAddr', 'text', 100, 0, 0, '', 0, '入货通知详情', 1, NULL, NULL, NULL, NULL, 0),
	(32, 'notifyGoods', '船代', 'shippingAgent', 'text', 100, 0, 0, '', 0, '入货通知详情', 1, NULL, NULL, NULL, NULL, 0),
	(33, 'notifyGoods', '船代联系人', 'shippingAgentContent', 'text', 100, 0, 0, '', 0, '入货通知详情', 1, NULL, NULL, NULL, NULL, 0),
	(34, 'notifyGoods', '船代网址', 'shippingAgentWebsite', 'text', 100, 0, 0, '', 0, '入货通知详情', 1, NULL, NULL, NULL, NULL, 0),
	(35, 'notifyGoods', '船代备注', 'shippingAgentRemark', 'text', 100, 0, 0, '', 0, '入货通知详情', 1, NULL, NULL, NULL, NULL, 0);
