INSERT INTO `s_data_rule` VALUES (25, '过滤系统账户', 'is_sys_account', '=', '0', '2017-9-19 15:22:48', '1', 'sys_admin', '2017-9-21 09:53:34', '1', 'sys_admin', '183', NULL);
INSERT INTO `s_data_rule` VALUES (31, '过滤非可用角色', 'delete_flag', '=', '0', '2017-9-22 10:14:23', '1', 'sys_admin', '2017-9-22 10:14:23', '1', 'sys_admin', '185', NULL);
INSERT INTO `s_data_rule` VALUES (32, NULL, 'is_sys_account', '=', '0', NULL, NULL, NULL, NULL, NULL, NULL, '11', 211);
INSERT INTO `s_data_rule` VALUES (33, '隐藏xxyy字段', 'is_sys_account', '=', '0', NULL, NULL, NULL, NULL, NULL, NULL, '11', 212);
INSERT INTO `s_data_rule` VALUES (34, '隐藏xxyy字段', 'is_sys_account', '=', '0', NULL, NULL, NULL, NULL, NULL, NULL, '11', 213);
INSERT INTO `s_data_rule` VALUES (35, '隐藏xxyy字段', 'is_sys_account', '=', '0', NULL, NULL, NULL, NULL, NULL, NULL, '11', 214);
INSERT INTO `s_data_rule` VALUES (36, 'asd', 'asd', 'asd', 'asd', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 221);
INSERT INTO `s_data_rule` VALUES (37, 'asd', 'asd', 'asd', 'asd', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 228);
INSERT INTO `s_data_rule` VALUES (38, 'ff', 'ff', 'ff', 'ff', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 229);
INSERT INTO `s_data_rule` VALUES (39, 'a', 'a', 'a', 'a', NULL, NULL, NULL, NULL, NULL, NULL, '184', 230);
INSERT INTO `s_data_rule` VALUES (40, 'asd', 'asd', 'asd', 'asd', NULL, NULL, NULL, NULL, NULL, NULL, '184', 231);
INSERT INTO `s_data_rule` VALUES (41, 'asd', 'asd', 'df', 'df', NULL, NULL, NULL, NULL, NULL, NULL, '185', 232);
INSERT INTO `s_data_rule` VALUES (42, 'asd', 'asd', 'asd', 'asd', NULL, NULL, NULL, NULL, NULL, NULL, '191', 235);
INSERT INTO `s_data_rule` VALUES (43, '45', 'yu', 'htr', 'hg', NULL, NULL, NULL, NULL, NULL, NULL, '192', 246);
INSERT INTO `s_data_rule` VALUES (44, 'fdh', 'fgh', 'fgh', 'fgh', NULL, NULL, NULL, NULL, NULL, NULL, '192', 247);
INSERT INTO `s_data_rule` VALUES (45, '222', '111', '222', '1', NULL, NULL, NULL, NULL, NULL, NULL, '192', 253);
INSERT INTO `s_data_rule` VALUES (46, 'y', 'y', 'y', 'y', NULL, NULL, NULL, NULL, NULL, NULL, '195', 259);
INSERT INTO `s_data_rule` VALUES (47, 'u', 'u', 'u', 'u', NULL, NULL, NULL, NULL, NULL, NULL, '195', 260);
INSERT INTO `s_data_rule` VALUES (48, 'A', 'S', 'D', 'D', NULL, NULL, NULL, NULL, NULL, NULL, '198', 270);
INSERT INTO `s_data_rule` VALUES (49, 'asd', 'asd', 'd', 'd', NULL, NULL, NULL, NULL, NULL, NULL, '198', 271);
INSERT INTO `s_data_rule` VALUES (50, 'bb', 'id', 'like', '\'#{id}\'', NULL, NULL, NULL, NULL, NULL, NULL, '248', 274);
INSERT INTO `s_data_rule` VALUES (51, 'v', 'v', 'v', 'v', NULL, NULL, NULL, NULL, NULL, NULL, '248', 275);
